mysite/photos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^clear/$', views.clear_database, name='clear_database'),
    url(r'^upload/$', views.ProgressBarUploadView.as_view(), name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^photos/', include('mysite.photos.urls', namespace='photos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/photos/models.py
from __future__ import unicode_literals

from django.db import models
from mysite.utils import util, constants




def custom_upload_location(instance, filename):
	file_extension = filename.split(".")
	if file_extension[-1] in constants.VIDEO_FILES:
		file_type = "video"
	else:
		file_type = "image"
	path = util.check_and_create_folder_complete_path(file_type)
	timestamp = util.get_current_timestamp()
	path = path + "/" + str(timestamp)+"_"+filename
	return path

class Photo(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=custom_upload_location)
    uploaded_at = models.DateTimeField(auto_now_add=True)

mysite/photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file', )

mysite/photos/views.py
import time

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import PhotoForm
from .models import Photo
import os, sys
from django.conf import settings
from mysite.utils import util, constants

class ProgressBarUploadView(View):
    def get(self, request):
        media_paths = {}
        files = []
        path = settings.MEDIA_ROOT + "/uploads"
        for dirpath, dirnames, filenames in os.walk(path):
            for f in filenames:
                file_path =  os.path.join(dirpath, f) 
                file_dir = {f: constants.RELATIVE_PATH + file_path.split("/media")[-1]}
                media_paths = util.get_path_dict_from_path(dirpath, media_paths, file_dir)                
        print media_paths
        photos_list = Photo.objects.all()
        return render(self.request, 'photos/upload/index.html', {'photos': photos_list, 'media_paths': media_paths})

    def post(self, request):
        # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
        time.sleep(1)  
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)

def clear_database(request):
    for photo in Photo.objects.all():
        photo.file.delete()
        photo.delete()
    return redirect(request.POST.get('next'))

mysite/photos/templates/photos/base.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" action="{% url 'photos:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
  </form>
  <h1 class="page-header">
    My Drive
    <small>/ {% block title %}{% endblock %}</small>
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default"> 
        <div class="list-group">
          <a href="{% url 'photos:upload' %}" class="list-group-item{% if request.path == '/photos/upload/' %} active{% endif %}">
            Bulk Upload
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      {% block photos_content %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

mysite/photos/templates/photos/upload/index.html
{% extends 'photos/base.html' %}

{% load static %}

{% block title %}Bulk Upload{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'photos/js/progress-bar-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload Media
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'photos:upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>Photo</th>
      </tr>
    </thead>
    <tbody>
      <td>
      {% for year, year_value in media_paths.items %}
        {{year}}        
        {% for month, month_value in year_value.items %}
          <br/>&ensp;&ensp;|--{{month}}
            {% for day, day_value in month_value.items %}
              <br/>&ensp;&ensp;&ensp;&ensp;|--{{day}}
                {% for media_type, media_files in day_value.items %}
                <br/>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;|--{{media_type}}
                    {% for file in media_files %}
                      {% for filename, url in file.items %}
                        <br/>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;|--<a href="{{ url }}">{{ filename }}</a>
                      {% endfor %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        {% endfor %}
      {% endfor %}
      </td>
    </tbody>
  </table>

  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mysite/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Photos Library - Simple is Better Than Complex{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="page-header">Multiple File Upload Example</h1>
  <hr>
  <ul>
    <li><a href="photos/upload/">Client here to Start </a></li>
  </ul>
{% endblock %}

mysite/templates/includes/header.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'photos:upload' %}">My Drive</a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
    </div>
  </div>
</nav>